[phases.setup]
nixPkgs = ['python311', 'python3Packages.virtualenv']

cmds = [
  "cd Server-Setup && python3 -m venv venv",
  "cd Server-Setup && source venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "cd Server-Setup && source venv/bin/activate && gunicorn server:app"
