INSERT INTO stadium VALUES
(1, 'Ball Arena', 'Denver, Colorado', 19,200, 356),
(2, 'Barclays Center', 'Brooklyn, New York', 17732, 750),
(3, 'Capital One Arena', 'Washington, D.C.', 20356, 1000),
(4, 'Chase Center', 'San Francisco, California', 18064, 700),
(5, 'Delta Center', 'Salt Lake City, Utah', 18306, 367),
(6, 'Frost Bank Center', 'San Antonio, Texas', 18418, 9),
(7, 'Golden 1 Center', 'Sacramento, California', 17583, 665),
(8, 'Kaseya Center', 'Miami, Florida', 19600, 2),
(9, 'Little Caesars Arena', 'Detroit, Michigan', 20332, 100),
(10, 'Madison Square Garden', 'New York City, New York', 19812, 959);