#!/bin/bash

output="COMBINED_CREATE.sql"

# Empty the output file if it exists
> "$output"

# Loop through all .sql and .SQL files, excluding the output file
for file in *.sql *.sqL *.SQL; do
    if [[ -f "$file" && "$file" != "$output" ]]; then
        # echo "-- START OF: $file" >> "$output"
        cat "$file" >> "$output"
        echo -e "\n" >> "$output"
        # echo -e "\n-- END OF: $file\n" >> "$output"
        # echo -e "\n-- -------------------------\n" >> "$output"
    fi
done
