SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `ratingAuditlog`;
DROP TABLE IF EXISTS `rating`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `match`;
DROP TABLE IF EXISTS `playoff`;
DROP TABLE IF EXISTS `donation`;
DROP TABLE IF EXISTS `player`;
DROP TABLE IF EXISTS `referee`;
DROP TABLE IF EXISTS `team`;
DROP TABLE IF EXISTS `bracket`;
DROP TABLE IF EXISTS `streaming_service`;
DROP TABLE IF EXISTS `conference`;
DROP TABLE IF EXISTS `sponsor`;
DROP TABLE IF EXISTS `stadium`;
DROP TABLE IF EXISTS `coach`;
SET foreign_key_checks = 1;